--- !ruby/object:VR_ENV
settings_file_version: 1
width: 1855
height: 1056
panel_pos: 360
run_command_line: ruby main.rb
open_files:
- /home/griest/PokemonEssentialsEditor/main.rb
- /home/griest/PokemonEssentialsEditor/bin/MyClass.rb
open_folders:
- /home/griest/PokemonEssentialsEditor
- /home/griest/PokemonEssentialsEditor/bin
current_file: /home/griest/PokemonEssentialsEditor/bin/MyClass.rb
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
