require_relative 'lib/java_namespacing'
require_relative 'lib/kernel'
require_relative 'lib/util'
require_relative 'lib/pkmnee'
require_relative 'lib/plugin'
require_relative 'lib/rgss_internal'
require_relative 'lib/rgss_rpg'
require_relative 'lib/rgss_mod'
# require_relative 'lib/import'