# 9b79c9c4c9e318f1cda021b4ad9a4e2f995e72f8 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2016-07-08 17:13:54 +0800 for C:/Users/Peter/PokemonEssentialsEditor/res/fxml/plugin/map/map-view.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT166955504767b605a3a64b98b08f08d829d2a99c
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

with(__local_fxml_controller) do
 setId("border_pane")
 __local_fx_id_setter.call("border_pane", self)
 setBottom(build(Java::JavafxSceneControl::Label) do
  setId("info")
  __local_fx_id_setter.call("info", self)
  setText("Label")
  Java::JavafxSceneLayout::BorderPane.setAlignment(self, Java::javafx::geometry::Pos::CENTER)
 end)
 setCenter(build(Java::JavafxSceneControl::ScrollPane) do
  setId("map_scroll_pane")
  __local_fx_id_setter.call("map_scroll_pane", self)
  setPannable(true)
  setPrefHeight(200.0)
  setPrefWidth(200.0)
  Java::JavafxSceneLayout::BorderPane.setAlignment(self, Java::javafx::geometry::Pos::CENTER)
 end)
 setLeft(build(Java::JavafxSceneControl::ScrollPane) do
  setId("tileset_scroll_pane")
  __local_fx_id_setter.call("tileset_scroll_pane", self)
  setMaxWidth(-Infinity)
  setMinWidth(-Infinity)
  setPrefHeight(200.0)
  setPrefViewportWidth(256.0)
  setPrefWidth(274.0)
  Java::JavafxSceneLayout::BorderPane.setAlignment(self, Java::javafx::geometry::Pos::CENTER)
 end)
 setFocusTraversable(true)
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(800.0)
 setPrefWidth(1280.0)
end
    end

      def hash
        "9b79c9c4c9e318f1cda021b4ad9a4e2f995e72f8"
      end
      def compiled?
        true
      end
    end
  end
end
