# 0f40d364c48b34932b8af1ec21359d45fb1d5e69 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2016-07-08 17:07:19 +0800 for C:/Users/Peter/PokemonEssentialsEditor/res/fxml/plugin/map/toolbar.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT567b9e0f03464567b56db8dd0c37585bd5fdfe1e
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

with(__local_fxml_controller) do
 setId("toolbar")
 __local_fx_id_setter.call("toolbar", self)
 getItems.add(build(Java::JavafxSceneControl::Slider) do
  setId("map_scale_slider")
  __local_fx_id_setter.call("map_scale_slider", self)
  setBlockIncrement(0.25)
  setMajorTickUnit(0.25)
  setMax(1.0)
  setMin(0.25)
  setMinorTickCount(0)
  setShowTickLabels(true)
  setShowTickMarks(true)
  setSnapToTicks(true)
  setValue(1.0)
 end)
 getItems.add(build(Java::JavafxSceneControl::Separator) do
  setOrientation(Java::javafx::geometry::Orientation::VERTICAL)
  setPrefHeight(0.0)
  setPrefWidth(0.0)
 end)
 getItems.add(build(Java::JavafxSceneControl::ToggleButton) do
  setId("layer1_button")
  __local_fx_id_setter.call("layer1_button", self)
  setMnemonicParsing(false)
  setText("Layer 1")
 end)
 getItems.add(build(Java::JavafxSceneControl::ToggleButton) do
  setId("layer2_button")
  __local_fx_id_setter.call("layer2_button", self)
  setMnemonicParsing(false)
  setText("Layer 2")
 end)
 getItems.add(build(Java::JavafxSceneControl::ToggleButton) do
  setId("layer3_button")
  __local_fx_id_setter.call("layer3_button", self)
  setMnemonicParsing(false)
  setText("Layer 3")
 end)
 getItems.add(build(Java::JavafxSceneControl::Separator) do
  setOrientation(Java::javafx::geometry::Orientation::VERTICAL)
  setPrefHeight(0.0)
  setPrefWidth(0.0)
 end)
 setPrefHeight(48.0)
 setPrefWidth(745.0)
end
    end

      def hash
        "0f40d364c48b34932b8af1ec21359d45fb1d5e69"
      end
      def compiled?
        true
      end
    end
  end
end
