# 32f54f96414bdc3faa951ff6ecdd90e589dc58b3 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2016-05-27 01:26:36 -0400 for C:/Users/Peter/PokemonEssentialsEditor/layout/plugin-select.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOTb4676007b9b1a862f12cc3419e49714efc328af2
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

with(__local_fxml_controller) do
 getChildren.add(build(Java::JavafxSceneControl::SplitPane) do
  setId("splitpane")
  __local_fx_id_setter.call("splitpane", self)
  getItems.add(build(Java::JavafxSceneLayout::VBox) do
   setId("plugin_select_vbox")
   __local_fx_id_setter.call("plugin_select_vbox", self)
   getChildren.add(build(Java::JavafxSceneControl::Label) do
    setId("plugin_select_label")
    __local_fx_id_setter.call("plugin_select_label", self)
    setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0", "left"=>"5.0", "right"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
    end)
    setAlignment(Java::javafx::geometry::Pos::CENTER)
    setContentDisplay(Java::javafx::scene::control::ContentDisplay::CENTER)
    setText("Plugin Selection")
    setTextAlignment(Java::javafx::scene::text::TextAlignment::CENTER)
   end)
   getChildren.add(build(Java::JavafxSceneControl::ScrollPane) do
    setId("plugin_select_scrollpane")
    __local_fx_id_setter.call("plugin_select_scrollpane", self)
    setContent(build(Java::JavafxSceneControl::ListView) do
     setId("plugin_list")
     __local_fx_id_setter.call("plugin_list", self)
     setMaxHeight(1.7976931348623157e+308)
     setMaxWidth(1.7976931348623157e+308)
     setPrefHeight(560.0)
     setPrefWidth(377.0)
    end)
    setFitToHeight(true)
    setFitToWidth(true)
    setMaxHeight(1.7976931348623157e+308)
    setMaxWidth(1.7976931348623157e+308)
    setPrefHeight(336.0)
    setPrefWidth(504.0)
    Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
   end)
   setFocusTraversable(true)
  end)
  getItems.add(build(Java::JavafxSceneLayout::VBox) do
   setId("preview_vbox")
   __local_fx_id_setter.call("preview_vbox", self)
   getChildren.add(build(Java::JavafxSceneImage::ImageView) do
    setId("preview_imageview")
    __local_fx_id_setter.call("preview_imageview", self)
    Java::JavafxSceneLayout::VBox.setMargin(self, build(FxmlBuilderBuilder, {}, Java::JavafxGeometry::Insets) do
    end)
    setViewport(build(FxmlBuilderBuilder, {}, Java::JavafxGeometry::Rectangle2D) do
    end)
    setPickOnBounds(true)
    setPreserveRatio(true)
   end)
   setFillWidth(false)
  end)
  setDividerPositions(*[0.5])
  setFocusTraversable(true)
  setPrefHeight(-1.0)
  setPrefWidth(-1.0)
  Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
 end)
 getChildren.add(build(Java::JavafxSceneControl::ToolBar) do
  getItems.add(build(Java::JavafxSceneControl::Button) do
   setId("confirm_button")
   __local_fx_id_setter.call("confirm_button", self)
   setMnemonicParsing(false)
   setText("Open")
   setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "openPlugin"))
  end)
  getItems.add(build(Java::JavafxSceneControl::CheckBox) do
   setId("window_checkbox")
   __local_fx_id_setter.call("window_checkbox", self)
   setMnemonicParsing(false)
   setPrefHeight(25.0)
   setPrefWidth(160.0)
   setText("Open in new window")
  end)
  setPrefHeight(40.0)
  setPrefWidth(200.0)
 end)
 setPrefHeight(600.0)
 setPrefWidth(900.0)
end
    end

      def hash
        "32f54f96414bdc3faa951ff6ecdd90e589dc58b3"
      end
      def compiled?
        true
      end
    end
  end
end
