# 4066ff305f700126df92be454c0c8244b7cc136c encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2015-08-20 16:22:46 -0400 for /home/griest/pkmn-editor/PokemonEssentialsEditor/layout/plugin-select.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOTb4676007b9b1a862f12cc3419e49714efc328af2
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

with(__local_fxml_controller) do
 getChildren.add(build(Java::JavafxSceneControl::SplitPane) do
  getItems.add(build(Java::JavafxSceneLayout::VBox) do
   getChildren.add(build(Java::JavafxSceneControl::Label) do
    setPadding(build(FxmlBuilderBuilder, {"bottom"=>"5.0", "left"=>"5.0", "right"=>"5.0", "top"=>"5.0"}, Java::JavafxGeometry::Insets) do
    end)
    setAlignment(Java::javafx::geometry::Pos::CENTER)
    setContentDisplay(Java::javafx::scene::control::ContentDisplay::CENTER)
    setText("Plugin Selection")
    setTextAlignment(Java::javafx::scene::text::TextAlignment::CENTER)
   end)
   getChildren.add(build(Java::JavafxSceneControl::ScrollPane) do
    setContent(build(Java::JavafxSceneControl::ListView) do
     setId("plugin_list")
     __local_fx_id_setter.call("plugin_list", self)
    end)
    Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
   end)
   getChildren.add(build(Java::JavafxSceneLayout::TilePane) do
    getChildren.add(build(Java::JavafxSceneControl::Button) do
     setId("confirm_button")
     __local_fx_id_setter.call("confirm_button", self)
     setMnemonicParsing(false)
     setText("Open")
     setOnAction(EventHandlerWrapper.new(__local_fxml_controller, "open_plugin"))
    end)
    getChildren.add(build(Java::JavafxSceneControl::CheckBox) do
     setId("window_checkbox")
     __local_fx_id_setter.call("window_checkbox", self)
     setMnemonicParsing(false)
     setPrefHeight(25.0)
     setPrefWidth(160.0)
     setText("Open in new window")
    end)
    setPadding(build(FxmlBuilderBuilder, {"top"=>"5.0"}, Java::JavafxGeometry::Insets) do
    end)
    setFocusTraversable(true)
    setPrefHeight(200.0)
    setPrefWidth(200.0)
    setTileAlignment(Java::javafx::geometry::Pos::TOP_LEFT)
    Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::SOMETIMES)
   end)
   setFocusTraversable(true)
   setPrefHeight(578.0)
   setPrefWidth(244.0)
  end)
  getItems.add(build(Java::JavafxSceneLayout::AnchorPane) do
   setId("config_pane")
   __local_fx_id_setter.call("config_pane", self)
  end)
  setDividerPositions(*[0.3])
  setFocusTraversable(true)
  setPrefHeight(-1.0)
  setPrefWidth(-1.0)
  Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
 end)
 getChildren.add(build(Java::JavafxSceneLayout::HBox) do
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setFont(build(FxmlBuilderBuilder, {"size"=>"11.0"}, Java::JavafxSceneText::Font) do
    __local_fx_id_setter.call("x3", self)
   end)
   setTextFill(build(FxmlBuilderBuilder, {"blue"=>"0.625", "green"=>"0.625", "red"=>"0.625"}, Java::JavafxScenePaint::Color) do
    __local_fx_id_setter.call("x4", self)
   end)
   setMaxHeight(1.7976931348623157e+308)
   setMaxWidth(-1.0)
   setText("Left status")
   Java::JavafxSceneLayout::HBox.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
  end)
  getChildren.add(build(Java::JavafxSceneLayout::Pane) do
   setPrefHeight(-1.0)
   setPrefWidth(-1.0)
   Java::JavafxSceneLayout::HBox.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
  end)
  getChildren.add(build(Java::JavafxSceneControl::Label) do
   setFont(__local_fxml_controller.instance_variable_get(:@x3))
   setMaxWidth(-1.0)
   setText("Right status")
   setTextFill(__local_fxml_controller.instance_variable_get(:@x4))
   Java::JavafxSceneLayout::HBox.setHgrow(self, Java::javafx::scene::layout::Priority::NEVER)
  end)
  setPadding(build(FxmlBuilderBuilder, {"bottom"=>"3.0", "left"=>"3.0", "right"=>"3.0", "top"=>"3.0"}, Java::JavafxGeometry::Insets) do
  end)
  setId("HBox")
  setAlignment(Java::javafx::geometry::Pos::CENTER_LEFT)
  setSpacing(5.0)
  Java::JavafxSceneLayout::VBox.setVgrow(self, Java::javafx::scene::layout::Priority::NEVER)
 end)
 setPrefHeight(600.0)
 setPrefWidth(900.0)
end
    end

      def hash
        "4066ff305f700126df92be454c0c8244b7cc136c"
      end
      def compiled?
        true
      end
    end
  end
end
