# 7c1cb46b26a2f6ca0da19e836bacf287f701fc3b encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2015-05-23 17:18:39 -0400 for /home/griest/pkmn-editor/PokemonEssentialsEditor/layout/editor-data.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOTbbf272b214edb1d3d421ca3032d57f9b69d4e4c3
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end

build(Java::JavafxSceneLayout::AnchorPane) do
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 getChildren.add(build(Java::JavafxSceneControl::TreeTableView) do
  setId("data_tree_view")
  __local_fx_id_setter.call("data_tree_view", self)
  setLayoutX(10.0)
  setLayoutY(10.0)
  setPrefHeight(400.0)
  setPrefWidth(600.0)
  Java::JavafxSceneLayout::AnchorPane.setBottomAnchor(self, 0.0)
  Java::JavafxSceneLayout::AnchorPane.setLeftAnchor(self, 0.0)
  Java::JavafxSceneLayout::AnchorPane.setRightAnchor(self, 0.0)
  Java::JavafxSceneLayout::AnchorPane.setTopAnchor(self, 0.0)
 end)
 setMaxHeight(-Infinity)
 setMaxWidth(-Infinity)
 setMinHeight(-Infinity)
 setMinWidth(-Infinity)
 setPrefHeight(400.0)
 setPrefWidth(600.0)
end
    end

      def hash
        "7c1cb46b26a2f6ca0da19e836bacf287f701fc3b"
      end
      def compiled?
        true
      end
    end
  end
end
